SRC += fightstick.c

OLED_ENABLE = no
OLED_DRIVER = ssd1306
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
MUSIC_ENABLE = no
DYNAMIC_MACRO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
TRI_LAYER_ENABLE = yes
SPLIT_KEYBOARD = yes
QMK_SETTINGS = no
MOUSEKEY_ENABLE = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = no
SPLIT_HAPTIC_ENABLE = no

#PER KEY RGB
RGB_MATRIX_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
VIALRGB_ENABLE = no
VIAL_INSECURE = yes

NKRO_ENABLE = yes

JOYSTICK_ENABLE = yes
JOYSTICK_DRIVER = digital

